env:
    global:
        - LD_LIBRARY_PATH: /usr/local/lib
script:
  - cargo build
  - make all
install:
  - curl https://static.rust-lang.org/rustup.sh | sudo sh
script:
  - rustc --version
  - cargo --version
  - cargo build -v
  - cargo test -v
notifications:
    email:
        - damien.schoof+github@gmail.com
